//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.14 at 08:17:26 PM CEST 
//


package de.igg.citygmldiff.citygmldiff.editscript.jaxb;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for EditOperationType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="EditOperationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="xPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EditOperationType", propOrder = {
        "xPath"
})
@XmlSeeAlso({
        UpdateOperationType.class,
        UncertainType.class,
        InsertDeleteOperationType.class
})
public abstract class EditOperationType {

    @XmlElement(required = true)
    protected String xPath;

    /**
     * Gets the value of the xPath property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getXPath() {
        return xPath;
    }

    /**
     * Sets the value of the xPath property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setXPath(String value) {
        this.xPath = value;
    }

}
