//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.14 at 08:17:26 PM CEST 
//


package de.igg.citygmldiff.citygmldiff.editscript.jaxb;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for InsertDeleteOperationType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="InsertDeleteOperationType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://igg.tu-berlin.de}EditOperationType">
 *       &lt;sequence>
 *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InsertDeleteOperationType", propOrder = {
        "value"
})
@XmlSeeAlso({
        DeleteOperationType.class,
        InsertOperationType.class
})
public abstract class InsertDeleteOperationType
        extends EditOperationType {

    @XmlElement(required = true)
    protected Object value;

    /**
     * Gets the value of the value property.
     *
     * @return possible object is
     * {@link Object }
     */
    public Object getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     *
     * @param value allowed object is
     *              {@link Object }
     */
    public void setValue(Object value) {
        this.value = value;
    }

}
