//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.14 at 08:17:26 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://igg.tu-berlin.de", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED) package de.igg.citygmldiff.citygmldiff.editscript.jaxb;
