//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.14 at 08:17:26 PM CEST 
//


package de.igg.citygmldiff.citygmldiff.editscript.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UncertainType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="UncertainType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://igg.tu-berlin.de}EditOperationType">
 *       &lt;sequence>
 *         &lt;element name="oldID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="newID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UncertainType", propOrder = {
        "oldID",
        "newID"
})
public class UncertainType
        extends EditOperationType {

    @XmlElement(required = true)
    protected String oldID;
    @XmlElement(required = true)
    protected String newID;

    /**
     * Gets the value of the oldID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOldID() {
        return oldID;
    }

    /**
     * Sets the value of the oldID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOldID(String value) {
        this.oldID = value;
    }

    /**
     * Gets the value of the newID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getNewID() {
        return newID;
    }

    /**
     * Sets the value of the newID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setNewID(String value) {
        this.newID = value;
    }

}
